# This is a basic workflow to help you get started with Actions

name: Publishing CI

# Controls when the action will run.
on:
  # run workflow manually
  workflow_dispatch:
    branches: [master]

# Run jobs automatically.
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publishing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up jdk version
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs build
      - run:
          echo "Publishing start..."
          ./gradlew publish
          echo "Publishing finished."
        env:
          PACKAGE_REPO_USERNAME: ${{ secrets.PACKAGE_REPO_USERNAME }}
          PACKAGE_REPO_TOKEN: ${{ secrets.PACKAGE_REPO_TOKEN }}
          PUBLISHING_SUB_VERSION: ${{ github.run_id }}